### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by AuspeXeu** [jpliew/Multi-Reader-Wiegand-Protocol-Library-for-Arduino#1]
Would be good to mention the dependency to https://github.com/NicoHood/PinChangeInterrupt in the installation section

**Comment by jpliew** [comment]
I have not been keeping up with Arduino development lately, I think PinChangeInterrupt might have already included in the official distro. I will still update the readme.

**Comment by AuspeXeu** [comment]
It wasn't working without installing it manually even on the latest IDE :)

**Comment by jpliew** [comment]
Thanks mate, I have updated the README.md
